In [1]:
import numpy as np

# Numbers and strings

In [2]:
# ints vs. floats

c = 7
d = 7.0

print(c,d)

7 7.0


In [3]:
print( type(c) )
print( type(d) )

<class 'int'>
<class 'float'>


In [6]:
# implication of datatype for functions loops

for i in range(c): # d generates an error
    print(i)

0
1
2
3
4
5
6


In [8]:
# we can add numbers; can we "add" strings??
firstName = 'E'
lastName  = 'T'

print( firstName + lastName )
print( firstName + ' ' + lastName )

ET
E T


In [9]:
firstName * 3

'EEE'

In [10]:
%whos

Variable    Type      Data/Info
-------------------------------
c           int       7
d           float     7.0
firstName   str       E
i           int       6
lastName    str       T
np          module    <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>


In [13]:
### converting across datatypes

s1 = '4'
s2 = '4.7'
n1 = 5
n2 = 5.8

## convert strings to integers
print( int(s1) )
# print( int(s2) ) generates an error


## string to floating-point
print( float(s1) )
print( float(s2) )


## number to string
print( str(n1) )
print( str(n2) )

4
4.0
4.7
5
5.8


# Lists and numpy arrays

In [14]:
aList = [0,1,2,3,4,5]
aList

[0, 1, 2, 3, 4, 5]

In [15]:
type(aList)

list

In [16]:
listList = [ 3,['3','4','5'],5,[4,5,6] ]
listList

[3, ['3', '4', '5'], 5, [4, 5, 6]]

In [17]:
listList = [ 
            3,              # a number
            ['3','h','5'],  # a list of strings
            5,              # another number
            [4,5,6]         # a list of numbers
           ]

listList

[3, ['3', 'h', '5'], 5, [4, 5, 6]]

In [18]:
aList = [0,1,2,3,4,5]
strList = ['0','1','2','3','4','5']

aList + strList
# aList + listList

[0, 1, 2, 3, 4, 5, '0', '1', '2', '3', '4', '5']

In [19]:
aList*3

[0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5]

In [20]:
aList_np = np.array(aList)

print(aList)
print(aList_np)

[0, 1, 2, 3, 4, 5]
[0 1 2 3 4 5]


In [21]:
print(aList*3)
print(aList_np*3)

[0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5]
[ 0  3  6  9 12 15]


In [24]:
# print(aList+3) generates an error
print(aList_np+3)

[3 4 5 6 7 8]


In [25]:
# regular method
for idx,item in enumerate(listList):
    print(f'List element {idx} is {item} and is of type {type(item)}.')

List element 0 is 3 and is of type <class 'int'>.
List element 1 is ['3', 'h', '5'] and is of type <class 'list'>.
List element 2 is 5 and is of type <class 'int'>.
List element 3 is [4, 5, 6] and is of type <class 'list'>.


In [26]:
# advanced method to print out only the type
for idx,item in enumerate(listList):
    t = str(type(item))[8:] 
    apost = t.find("'")
    print(f'List element {idx} is {item} and is of type {t[:apost]}.')

List element 0 is 3 and is of type int.
List element 1 is ['3', 'h', '5'] and is of type list.
List element 2 is 5 and is of type int.
List element 3 is [4, 5, 6] and is of type list.
